---
title: "Detailed schedule"
author:
  - name: Laura Maréchal
    affiliation: Univ. Bordeaux, UMR 5199 PACEA
    url: https://www.researchgate.net/profile/Laura-Marechal-2
    orcid_id: 0000-0001-7728-5196
  - name: Frédéric Santos
    affiliation: CNRS, UMR 5199 PACEA
    url: https://gitlab.com/f-santos
    orcid_id: 0000-0003-1445-3871
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Day 1 (Thursday, June 23, 2022)
```{r echo=FALSE}
library(flextable)
dat <- read.csv2("schedule/day1.csv", check.names = FALSE) |>
    flextable() |>
    merge_v(j = ~ Schedule) |>
    theme_vanilla()

set_table_properties(dat, width = 1, layout = "autofit")
```

## Day 2 (Friday, June 24, 2022)
```{r echo=FALSE}
dat <- read.csv2("schedule/day2.csv", check.names = FALSE) |>
    flextable() |>
    merge_v(j = ~ Schedule) |>
    theme_vanilla()

set_table_properties(dat, width = 1, layout = "autofit")
```

## Day 3 (Monday, June 27, 2022)
```{r echo=FALSE}
dat <- read.csv2("schedule/day3.csv", check.names = FALSE) |>
    flextable() |>
    merge_v(j = ~ Schedule) |>
    theme_vanilla()

set_table_properties(dat, width = 1, layout = "autofit")
```

## Day 4 (Tuesday, June 28, 2022)
```{r echo=FALSE}
dat <- read.csv2("schedule/day4.csv", check.names = FALSE) |>
    flextable() |>
    merge_v(j = ~ Schedule) |>
    theme_vanilla()

set_table_properties(dat, width = 1, layout = "autofit")
```

## Day 5 (Tuesday, June 29, 2022)
```{r echo=FALSE}
dat <- read.csv2("schedule/day5.csv", check.names = FALSE) |>
    flextable() |>
    merge_v(j = ~ Schedule) |>
    theme_vanilla()

set_table_properties(dat, width = 1, layout = "autofit")
```

